let SUGGESTIONS = [

“aww soñé con gatitos diminutos ahora que recuerdo”,
“ayer soñé que me sacaba un dos”,
“dormí siete minutos y soñé que tenía que bajar once pisos por una escalera hecha con sogas”, 
“dormí una siesta de cuatro horas y soñé que mi madre me contaba que había estado presa”,
“el otro día soñé que me leían los pies”,
“el otro día soñé que me soltaba”,
“en la siesta soñé que tenía que cuidar a una perrita llamada mulva”,
“las notificaciones de facebook están verdes o lo soñé”,
“no sé si soñé que me llegaba un mail o de verdad me llegó”,
“siempre soñé con trabajar en emirates”,
“soñé algo horrible”,
“soñé algo que me mató para siempre”,
“soñé algo re trascendente”,
“soñé con 500000 australes en droga”,
“soñé con adriana cortés y que nos perseguía el nazismo”,
“soñé con betty draper”,
“soñé con boy olmi”,
“soñé con brazos cortados y gelatina de droga con forma de dientes”,
“soñé con brea”,    
“soñé con brianna era el último día que la veía y me daba pena estábamos en la residencia”,
“soñé con código”,
“soñé con desmond”,
“soñé con el curso de lingüística general con lo que dice el curso de lingüística general”,
“soñé con el estado era como una casa en la que me sentía bien”,
“soñé con el whatsapp”,
“soñé con él”,
“soñé con florencia y con el abogado”,
“soñé con joaquín y su querida incomprensión”,
“soñé con la casa x”,
“soñé con la ciénaga”,
“soñé con la copa menstrual”,
“soñé con la ginecóloga con el psicólogo y con el oncólogo”,
“soñé con la mochila de una compañera del colegio”,
“soñé con la palabra delay eso fue hace unos días”,
“soñé con la pérdida del reino de bianco y tenía como nostalgia de la época en que la leía”,
“soñé con la telenovela errante”,
“soñé con la virgen maría”,
“soñé con la wii”,
“soñé con laura wittner”,
“soñé con mamá estaba tan nítida”,
“soñé con mariposas gigantes que me hablaban”,
“soñé con marruecos”,
“soñé con mi chakra raíz”,
“soñé con mi ex psicólogo”,
“soñé con mi mamá y con otra persona que se llama igual a ella”,
“soñé con ropa vintage”,
“soñé con san cayetano me hablaba pero tenía cuerpo de estatua”,
“soñé con san la muerte”,
“soñé con sartre pero no puedo recordar qué”,
“soñé con telas y con roland barthes”,
“soñé con toda la extensión del conurbano bonaerense en un mismo sueño”,
“soñé con un animal perfecto”,
“soñé con un arma”,
“soñé con un asesino”,
“soñé con un dinosaurio lila”,
“soñé con un epígrafe”,
“soñé con un lobo marino re lindo”,
“soñé con un lugar mágico al que podía acceder desde mi casa”, 
“soñé con un músculo”,
“soñé con un pájaro azul”,
“soñé con un papá noel con una dentadura exagerada”,
“soñé con un perro que tenía un palo de selfie en el culo con una gopro y te iba mostrando un recorrido muy a jugar con hugo”,
“soñé con un piso 17 porque soy una desgraciada”,
“soñé con un poema de vallejo”,
“soñé con un superhéroe”,
“soñé con un velorio chino”,
“soñé con una catarata”,
“soñé con una fiesta brian”,
“soñé con una música increíble”,
“soñé con una villa”,
“soñé con uno”,
“soñe con vos pasabas con un globo naranja de los que flotan parecías contento”, 
“soñé la parte que me dormí en la película de jodorowsky y ahora entiendo por qué jaime tiene las manos así”,
“soñé q era el fin del mundo había colectivos a los nuevos planetas subía néstor kirchner y no tenía cargada la sube nosotros le pagábamos el boleto”,
“soñé q era lunes y me había olvidado de ir a trabajar”,
“soñé que abrazaba una nube en un edificio muy alto”,
“soñé que alberto me convidaba cerveza en un tupper”,
“soñé que alguien con mi mismo nombre se moría por no poder cumplir un pacto con el diablo”,
“soñé que alguien decía pero la muerte es agramatical”,
“soñé que alguien decía y si no somos inmortales porque no tomamos las decisiones correctas”,
“soñé que alguien dejaba mi abrigo debajo de la lluvia”,
“soñé que alguien en videollamada buscaba sus anteojos y yo los encontraba en mi casa”,
“soñé que alguien me decía que ahora significaba en el pasado”,
“soñé que atendía el teléfono”,
“soñé que austria había cambiado de lugar en el mapa”,
“soñé que borges era literatura sin tacc”,
“soñé que buceaba en un bosque tipo twin peaks que me daba miedo”,
“soñé que buscaba en google y los resultados no eran personalizados era muy ominoso”,
“soñé que caminaba de noche por una avenida que después se hacía ruta después se hacía puente y desembocaba en un barco el barco me llevaba y yo pensaba uh pero si me lleva a otro país no tengo documento de repente aparecía la otra fernanda mugica y yo le robaba el documento”,
“soñé que cogíamos”,
“soñé que comía arena y me preguntaba si me haría mal a los dientes”,
“soñé que compraba con €€€”,
“soñé que con lumpenar comprábamos calabazas en toledo e intentábamos cambiar las etiquetas del precio por otras más baratas”,
“soñé que con maría rosario teníamos que ir a chapadmalal y nos tomábamos un bondi que iba a polonia”,
“soñé que conocía el peso exacto de tus piernas”,
“soñé que construíamos una casa en el mar echaba raíces y teníamos que declararla en afip”,
“soñé que corría desquiciadamente para recuperar un paraguas blanco”,
“soñé que daba clases de cocinar en el aula del colegio con una hornalla carcelaria y aceite hirviendo”,
“soñé que desataba un nudo enorme”,
“soñé que descubría que siempre que aparecía una perra en literatura era la misma perra y decía guau esta perra ya había aparecido en un cuento de lugones y está acá qué loco guau”,
“soñé que devenía sdf y una profesora de la facultad me preguntaba por qué no había ido más a bañarme a su casa”,
“soñé que discutía la pasiva con se”,
“soñé que discutía sobre si horacio quiroga era argentino o uruguayo”, 
“soñé que el árbol de la puerta de casa era un limonero”,
“soñé que el auto estaba lleno de papeles que me tapaban la cara”, 
“soñé que el cielo estaba contaminado y había latas gigantes flotando tipo dibujo animado”,
“soñé que el hoy era un lugar a donde venían a parar todos los perros perdidos”,
“soñé que el mar crecía y no había forma de subir al acantilado”, 
“soñé que elegía mal”,
“soñé que elegíamos lugares a donde ir en un mapa lleno de cadenas montañosas”,
“soñé que en luro y san juan había una frontera la cruzábamos de la mano”, 
“soñé que encontraba un libro de poemas de roque vaca narvaja”,
“soñé que era el 2066 y caminaba sola en un supermercado toledo”,
“soñé que era el fin del mundo, yo tenía una fiesta en ny e iba igual”,
“soñé que éramos amigas”,
“soñé que eras yihadista”,
“soñé que escribía un libro sobre la nieve”,
“soñé que estaba allá”,
“soñé que estaba borracha”,
“soñé que estaba empecinada”,
“soñé que estaba en la orilla y me llevaba el mar”,
“soñé que estaba toda golpeada”,
“soñé que flavia y rodrigo me saludaban desde un auto”, 
“soñé que godard había filmado una película en mar del plata en 1950”,
“soñé que gritaba hay jerarquías”,
“soñé que había nutella blanco”,
“soñé que había una aplicación para ubicar contenedores en la ciudad”,
“soñé que había una combinación de movimientos del cuerpo con la que te morías”,
“soñé que había una fiesta en lo de mis vecinos jorge y laura”,
“soñé que habían puesto transporte público en el mar un tren que te llevaba de un lado a otro de la ciudad por el agua”,
“soñé que hablaba con arlt”,
“soñé que hablaba con las pussy riot y que una ráfaga de viento me partía el cuerpo en dos”,
“soñé que hacía surf en una escollera”,
“soñé que iba a comprar comida para llevar a un restaurant bajo el agua”,
“soñé que iba a la peatonal sin barbijo me daba cuenta y todo se ponía cámara lenta no podía avanzar doblaba en una calle y era un callejón sin salida había policías por todas partes”,
“soñé que iba a toledo y compraba yerba uruguaya para diego y papel de fumar de los rugrats para flavia”,
“soñé que iba a un cumpleaños y estaban todos en silencio”,
“soñé que iba al anamora con fabián iriarte”,
“soñé que iba al cine estaba de espaldas a la pantalla veía al público reírse cuando miraba la pantalla veía que lo que se proyectaba era el público riéndose y comiendo pochoclo”,
“soñé que iba con la gata a una cervecería y teníamos toda una conversación”,
“soñé que juan ariel gomez me decía sos un embole en blanco y negro”, 
“soñé que jugaba al billar con bolas que flotaban en el aire a la altura de mis ojos”,
“soñé que la cátedra de teoría y crítica literarias ii la dictaba lucho avilés”,
“soñé que la gata jugaba en la ventana a través del vidrio con un gato igual a ella pero pájaro vi volar un gatito en mi sueño era hermoso”,
“soñé que la hermana de maría era un androide”,
“soñé que la tortuga era un ser expresivo que me quería estábamos en el patio”,
“soñé que le daba un abrazo a mi prima”,
“soñé que le daba una bebé a los lobos”,
“soñé que le decía a alguien a vos te va a encantar goodreads”,
“soñé que le decía a alguien suerte éxitos lo que haga falta”,
“soñé que le escribía un mensaje a alguien en la parte de atrás de una porción de pizza”,
“soñé que le pedía a mi ex analista que me recomendara un analista para ir de oyente”,
“soñé que le preguntaba a mamá de dónde había sacado cada una de sus plantas”,
“soñé que manejaba en una oscuridad absoluta”,
“soñé que manejaba y no sabía pasar los cambios”,
“soñé que manuel gálvez cantaba una canción de lana del rey”,
“soñé que maría levantaba vuelo con un paracaídas y volaba re feliz”,
“soñé que marie kondo se quedaba con toda mi ropa”,
“soñé que mario ortiz me decía el año que viene se van a usar los aparatos sin dientes”,
“soñé que masticaba mis propios dientes”,
“soñé que me apuntabas con un arma”,
“soñé que me baleaban”,
“soñé que me bardeaba una gurú del twitter y yo le decía y vos sos una gurú del twitter”,
“soñé que me casaba con mi némesis por compromiso”,
“soñé que me decías que en lugar de apellido debería llevar un relincho”,
“soñé que me desaprobaban el final de hispano i porque iba a rendir con una heladerita de playa”,
“soñé que me desvanecía pero en un teatro”,
“soñé que me diagnosticaban fatiga crónica”,
“soñé que me echaban y me sangró la nariz durante la noche”,
“soñé que me encarcelaban por meter una moneda de otro país en una máquina de gaseosas”,
“soñé que me encontraba a conmigotampoco comprando en el aragone”,
“soñé que me encontraba con mamá”,
“soñé que me engañabas”,
“soñé que me había vuelto loca y por eso no iba a trabajar”,
“soñé que me hacía amiga de un cura remisero que me llevaba a bailar a chocolate”,
“soñé que me hundía”,
“soñé que me la ponía en una rotonda”,
“soñé que me lavaban la cabeza para lavarme las ideas y después me quedaba ciega”,
“soñé que me llamaba nicolás”,
“soñé que me mudaba”, 
“soñé que me perseguía una ranita blanca”,
“soñé que me robaban la médula”,
“soñé que me suicidaba en otro idioma”,
“soñé que me teñía de rosa”,
“soñé que me tiraba de un acantilado”,
“soñé que mi padre me pasaba por al lado como un refilón una especie de metasueño”,
“soñé que mi padre me regalaba una bolsa de consorcio”,
“soñé que militaba en un mar en rusia”,
“soñé que nadie me quería y yo me enojaba”,
“soñé que nadie venía a mi cumpleaños”,
“soñé que néstor me estornudaba en la cara nestornudaba”,
“soñé que no existían las pocas personas que realmente quiero”,
“soñé que no me perdía en barajas”,
“soñé que no me podía dormir en australia y que caían caballos del cielo”,
“soñé que no me podían operar porque me olvidaba de hacer el ayuno tenía que explicarle al médico y me decía ah un olvido freudiano”,
“soñé que no podía expresar el principio de expresabilidad”,
“soñé que no podía hablar y me sangraba mucho la nariz”,
“soñé que no recordaba la lista de cosas que repito siempre antes de salir”,
“soñé que nos atacaban policías desde autos voladores”,
“soñé que pagaba con cinco pesos”,
“soñé que podía convertir una foto raw a jpg”,
“soñé que ponía chubby checker para bailar y alguien lo cambiaba y ponía una canción triste de calamaro y se reía de mí”,
“soñé que ponía unas fichas en el casino y salían unos pájaros que hacían una coreografía”,
“soñé que presenciaba el parto de frankenstein”,
“soñé que robaba monedas de la fuente de una ciudad de juguete”,
“soñé que rocío me decía los gatos negros no perdonan y rocío soñó con un gato negro y ahora me manda foto de un gato negro”,
“soñé que salía con guantes de lavar a la calle como prenda de vestir”,
“soñé que salvaba a gente de un incendio y no me agradecían se me quemaba la bufanda”,
“soñé que se había muerto cristina”,
“soñé que se me habían gastado los dientes de hacerlos rechinar”,
“soñé que se moría la leona selekta”,
“soñé que si cambiaba una letra de mi nombre me transformaba en otra persona y vos no me querías”,
“soñé que te morías”,
“soñé que tenía alzheimer”,
“soñé que tenía diócesis diócesis era una enfermedad”,
“soñé que tenía la presión alta”,
“soñé que tenía que rendir hispano iii”,
“soñé que tenía sueño y andaba por la vida sin poder abrir los ojos”,
“soñé que tenía un motor en la mandíbula”,
“soñé que tenía una pantera que era buena solamente conmigo”,
“soñé que tomaba horas para trabajar en el baño de un boliche”,
“soñé que trabajaba para scioli”,
“soñé que un alumno me lavaba los platos”,
“soñé que un bebé me decía me quiero morir”,
“soñé que un médico que me gustaba me invitaba a salir en el consultorio”,
“soñé que un montón de zombies judíos venían a mar del plata”,
“soñé que un patinador que siempre veo por la costa era una criatura no humana que había puesto la municipalidad para vigilar”,
“soñé que un perro me atacaba”,
“soñé que un tal gabriel dipasquale se presentaba a la ayudantía de argentinas”,
“soñé que una serpiente nos atacaba”,
“soñé que valentín me decía hola”,
“soñé que vendían droga en el cartucho feliz”,
“soñé que vivía en casa ludwig van beethoven”,
“soñé que volaba una sombrilla en la playa y se me clavaba en el dedo gordo del pie”,
“soñé que volvía a casa en un trineo comandado por caniches gigantes”,
“soñé que volvía a dax”,
“soñé que volvía nati”,
“soñé tantas veces que manejaba sin saber”,
“soñé toda la noche con una señora”,
“soñé toda la noche cosas horribles”,
“soñé toda una película sobre la segunda guerra mundial terminaba y aparecían andrea del boca y segundo cernadas en canal ocho”,
“soñé un mar muy transparente”,
“soñé un videojuego”,
“soñé una temporada nueva y entera de breaking bad diego era walter white”,
“soñé x y se me enrareció la vida”,
“sueño recurrente en el que un tipo me tiene encerrada e intento escapar pienso tengo las llaves corro cierro la puerta y lo encierro a él despierto con el corazón a recontra mil”,
“también soñé con pokèmon”,
“también soñé que era 1999 y le anteponíamos un 4 a los números de teléfono”,
“también soñé que llevaba a mis alumnos a un paseo y se perdían todos y los tenía que pagar”,
“también soñé que vermelho era verde”,
“tb soñé que había una luciérnaga adentro de la casa”,
“tengo lo que soñé en la punta de la lengua”,
“todavía no soñé con ella”,
“tres siestas soñé que sabía chino”
  


];

SUGGESTIONS.sort(function (x, y) {
  return strcmp(x, y);
});

function normalize(str) {
  return str.replace(/á/gi, 'a')
            .replace(/é/gi, 'e')
            .replace(/í/gi, 'i')
            .replace(/ó/gi, 'o')
            .replace(/ú/gi, 'u');
}

function strcmp(str1, str2) {
  return normalize(str1).localeCompare(normalize(str2));
}

function strle(str1, str2) {
  return strcmp(str1, str2) <= 0;
}

function streq(str1, str2) {
  return strcmp(str1, str2) === 0;
}

let MAX_RESULTS = 10;
function get_suggestions(prefix) {
  let i = 0;
  let j = SUGGESTIONS.length;
  while (i + 1 < j) {
    let m = Math.floor((i + j) / 2);
    if (strle(SUGGESTIONS[m], prefix)) {
      i = m;
    } else {
      j = m;
    }
  }
  let res = [];
  for (let k = i; k < SUGGESTIONS.length && k < i + MAX_RESULTS; k++) {
    if (streq(SUGGESTIONS[k].substr(0, prefix.length), prefix)) {
      res.push(SUGGESTIONS[k]);
    }
  }
  return res;
}

