
let NAMES = [
   
  "soñé",
  ];

let VERSES = {
  "soñé": [
    "soñé que te daba una cachetada",
    "soñé que no",
    "me dormí un ratito y soñé",
    "que te quebrabas las dos plantas de los pies",
    "",
    "soñé con el techo de villa silvina",
    "soñé que tenía diócesis",
    "diócesis era una enfermedad",
    "tengo diócesis decía                  y lloraba",
    "",
    "soñé con vos",
    "pasabas con un globo naranja ",
    "de los que flotan",
    "parecías contento",
    "",
    "soñé que me mudaba",
    "soñé que el auto estaba lleno de papeles",
    "que me tapaban la cara",
    "soñé que el mar crecía y no había forma de subir al acantilado", 
     "",
    "soñé que flavia y rodrigo me saludaban desde un auto",
    "soñé que en luro y san juan había una frontera",
    "cruzábamos de la mano",
    "soñé con un lugar mágico al que se podía entrar desde mi casa",
     "",
    "soñé que juan ariel gomez me decía sos un embole en blanco y negro",
    "dormí siete minutos y",
    "soñé que bajaba once pisos por una escalera hecha con sogas",
    "soñé que había una aplicación para ubicar contenedores", 
      "",
    "soñé que discutía ",
    "sobre si horacio quiroga era argentino o uruguayo ",
    "soñé con san cayetano ",
    "me hablaba pero tenía cuerpo de estatua ",
     "",
    "soñé que tenía que rendir hispano III",
    "soñé algo horrible",
    "soñé que me tiraba de un acantilado",
    "soñé con ropa vintage",
      "",
    "soñé que la tortuga",
    "era un ser expresivo que me quería",
    "estábamos en el patio",
    "soñé que escribía un libro sobre la nieve",
      "",
    "soñé que ponía chubby checker para bailar  ",
    "alguien lo cambiaba y ponía una canción triste de calamaro y se reía de mí ",
    "soñé que era el 2066 ",
    "caminaba sola en un supermercado toledo",
      "",
    "soñé  ",
    "soñé  ",
    "soñé  ",
    "soñé ",
  ]
   
 
};

