
let NAMES = [
   
  " soñé",
  "  soñé", 
  "   soñé", 
  "    soñé", 
  "     soñé", 
  "      soñé",
  "soñé      ",
  "soñé     ", 
  "soñé    ", 
  "soñé   ", 
  "soñé  ",
  "soñé ",
   
  
  ];

let VERSES = {
  " soñé": [
    "soñé que te daba una cachetada",
    "soñé que no",
    "me dormí un ratito y soñé",
    "que te quebrabas las dos plantas de los pies",
    "",
    "soñé con el techo de villa silvina",
    "soñé que tenía diócesis",
    "diócesis era una enfermedad",
    "tengo diócesis decía                  y lloraba",
    "",
    "soñé con vos",
    "pasabas con un globo naranja ",
    "de los que flotan",
    "parecías contento",
    "",
    "soñé que me mudaba",
    "soñé que el auto estaba lleno de papeles",
    "que me tapaban la cara",
     "",
    "soñé que el mar crecía y no había forma de subir al acantilado", 
     "",
    "soñé que flavia y rodrigo me saludaban desde un auto",
    "soñé que en luro y san juan había una frontera",
    "cruzábamos de la mano",
     "",
    "soñé con un lugar mágico al que se podía entrar desde mi casa",
    "soñé que juan ariel gomez me decía sos un embole en blanco y negro",
    "dormí siete minutos y soñé",
    "que bajaba once pisos por una escalera hecha con sogas",
    "soñé que había una aplicación para ubicar contenedores", 
     "",
    "soñé que discutía ",
    "sobre si horacio quiroga era argentino o uruguayo ",
    "soñé con san cayetano ",
    "me hablaba pero tenía cuerpo de estatua ",
     "",
    "soñé que tenía que rendir hispano III",
    "soñé algo horrible",
    "soñé que me tiraba de un acantilado",
    "soñé con ropa vintage",
      "",
    "soñé que la tortuga",
    "era un ser expresivo que me quería",
    "estábamos en el patio",
     ""  
   
  ],
   "  soñé": [
   "soñé que el árbol de la puerta de casa era un limonero",
     "soñé que si cambiaba una letra de mi nombre me transformaba en otra persona y vos no me querías",
     "aww soñé con gatitos diminutos ahora que recuerdo",
     "soñé que tenía una pantera que era buena solamente conmigo",
     "",
     "soñé con él", 
     "", 
     "soñé que Borges era literatura sin TACC", 
     "soñé con mariposas gigantes que me hablaban",
     "soñé que estaba empecinada", 
     "soñé un poema de Vallejo", 
     "soñé q era lunes y me había olvidado de ir a trabajar", 
     "", 
     "soñé que nos perseguía el nazismo", 
     "soñé con Marruecos", 
     "soñé con uno", 
     "soñé que daba clases de cocinar en el aula del colegio con una hornalla carcelaria y aceite hirviendo", 
     "soñé que tenía alzheimer", 
     "", 
     "soñé que volaba una sombrilla en la playa y se me clavaba en el dedo gordo del pie", 
     "soñé que estaba en la orilla y el mar me llevaba", 
     "soñé que me hacía amiga de un cura remisero. me llevaba a bailar a Chocolate",
     "", 
     "soñé que el hoy era un lugar a donde venían a parar todos los perros perdidos", 
     "", 
     "soñé que encontraba un libro de poemas de Roque Vaca Narvaja", 
     "soñé que Valentín me decía 'hola’", 
     "soñé que me echaban y me sangró la nariz durante la noche", 
     "soñé que Manuel Gálvez cantaba una canción de Lana del Rey", 
     "en la siesta soñé que tenía que cuidar a una perrita llamada Mulva", 
     "soñé que buceaba en un bosque tipo Twin Peaks y me daba miedo", 
     "soñé que María levantaba vuelo con un paracaídas y volaba re feliz", 
     ""
    
  ],
  "   soñé": [
      "soñé que estaba borracha", 
     "soñé que me hundía", 
     "soñé que nadie me quería y me enojaba", 
     "soñé con la ciénaga", 
     "", 
     "también soñé que llevaba a mis alumnos a un paseo. se perdían todos y los tenía que pagar", 
     "soñé que me robaban la médula", 
     "soñé que le preguntaba a mamá de dónde había sacado cada una de sus plantas", 
     "soñé con el curso de lingüística general, con lo que dice el curso de lingüística general", 
     "soñé que con María Rosario teníamos que ir a Chapadmalal y nos tomábamos un colectivo a Polonia", 
     "", 
     "soñé que jugaba al billar con bolas que flotaban en el aire a la altura de mis ojos", 
     "soñé que volvía Nati", 
     "el otro día soñé que me soltaba", 
     "soñé con una música increíble", 
     "", 
     "soñé que militaba en un mar en Rusia", 
     "", 
     "soñé que salía a la calle con guantes de lavar como prenda de vestir", 
     "soñé que cogíamos",                                
     "soñé X y se me enrareció la vida", 
     "soñé que iba a comprar comida para llevar a un restaurant bajo el agua", 
     "soñé que me baleaban",
     "", 
     "soñé con un superhéroe", 
     "soñé que el cielo estaba contaminado y había latas gigantes flotando tipo dibujo animado", 
     "soñé que me teñía de rosa", 
     "soñé con un piso 17 porque soy una desgraciada", 
     "todavía no soñé con ella",
     "", 
     "soñé que me casaba con mi némesis por compromiso", 
     "soñé que trabajaba para Scioli", 
     "soñé que eras yihadista", 
     "soñé con brazos cortados y gelatina de droga con forma de dientes", 
     "soñé con la copa menstrual", 
     "", 
     "soñé que me suicidaba en otro idioma", 
     "", 
     "soñé con un velorio chino", 
     "soñé la parte que me dormí en la película de jodorowsky y ahora entiendo por qué jaime tiene las manos así", 
     "soñé que éramos amigas", 
     "soñé con el estado. era como una casa en la que me sentía bien", 
     "soñé que manejaba en una oscuridad absoluta", 
     "", 
     "soñé que compraba con €€€", 
     "soñé con san la muerte", 
     "soñé que salvaba a gente de un incendio y no me agradecían. se me quemaba la bufanda", 
     "soñé que no podía expresar el principio de expresabilidad", 
     "soñé con brianna. era el último día que la veía y me daba pena. estábamos en la residencia"

         
  ], 
  "    soñé": [
     "soñé que me engañabas", 
     "soñé que un alumno me lavaba los platos", 
     "soñé que manejaba y no sabía pasar los cambios", 
     "soñé toda una película sobre la 2da guerra mundial. terminaba y aparecían andrea del boca y segundo cernadas en canal ocho", 
     "soñé que era el fin del mundo, yo tenía una fiesta en NY e iba igual", 
     "soñé que no recordaba la lista de cosas que repito siempre antes de salir", 
     "soñé con la ginecóloga, con el psicólogo y con el oncólogo", 
     "", 
     "soñé con una villa", 
     "soñé que alguien dejaba mi abrigo debajo de la lluvia", 
     "soñé que se moría la leona selekta", 
     "soñé que volvía a Dax", 
     "soñé que no me podía dormir en Australia y que caían caballos del cielo", 
     "soñé que gritaba '¡hay jerarquías!’", 
     "", 
     "soñé con una fiesta", 
     "tres siestas soñé que sabía chino", 
     "", 
     "soñé tantas veces que manejaba sin saber…", 
     "soñé que tenía sueño y andaba por la vida sin poder abrir los ojos", 
     "soñé que Austria había cambiado de lugar en el mapa", 
     "soñé un videojuego", 
     "soñé con 500.000 ARA en droga", 
     "", 
     "soñé con toda la extensión del conurbano bonaerense en un mismo sueño", 
     "soñé con un músculo", 
     "soñé con un arma", 
     "soñé con código", 
     "soñé algo re trascendente", 
     "soñé que podía convertir una foto raw a jpg", 
     "soñé con un papá noel con una dentadura exagerada", 
     "soñé que me lavaban la cabeza para lavarme las ideas y después me quedaba ciega", 
     "soñé que vivía en casa Ludwig van Beethoven", 
     "", 
     "soñé con Desmond", 
     "soñé con la palabra 'delay’, eso fue hace unos días", 
     "soñé que alguien me decía que 'ahora’ significaba 'en el pasado’", 
     "soñé con una catarata", 
     "", 
     "soñé que se había muerto cristina", 
     "soñé con el whatsapp", 
     "soñé que me interpelaban acerca de si realmente estaba de acuerdo con lo que estaba escribiendo", 
     "soñé con la mochila de una compañera del colegio", 
     "soñé que conocía el peso exacto de tus piernas", 
     "", 
     "soñé que estaba allá", 
     "soñé que se me habían gastado los dientes de hacerlos rechinar", 
     "soñé con un epígrafe", 
     "soñé que atendía el teléfono", 
     "soñé que tenía la presión alta", 
     "soñé que había nutella blanco", 
     "soñé con la wii", 
     "soñé que robaba monedas de la fuente de una ciudad de juguete"

  ], 
  "     soñé": [
     "soñé con la virgen maría",
     "soñé que no me perdía en barajas",
     "soñé con Joaquín y su querida incomprensión", 
     "soñé que desataba un nudo enorme",
     "",
     "soñé que un médico que me gustaba me invitaba a salir en el consultorio",
     "soñé que volvía a casa en un trineo comandado por caniches gigantes", 
     "soñé que me llamaba Nicolás",
     "soñé un mar muy transparente", 
     "",
     "soñé que te morías", 
     "", 
     "soñé que nadie venía a mi cumpleaños",
     "soñé que me desaprobaban el final de hispano I porque iba a rendir con una heladerita de playa",
     "soñé que hablaba con Arlt",
     "soñé que hacía surf en una escollera", 
     "soñé que me había vuelto loca y por eso no iba a trabajar",
     "también soñé que era 1999 y le anteponíamos un 4 a los números de teléfono",
     "soñé toda la noche cosas horribles",
     "soñé con la telenovela errante",
     "soñé con Laura Wittner",
     "soñé que presenciaba el parto de Frankenstein",
     "soñé con mamá, estaba tan nítida",
     "",
     "soñé que alguien con mi mismo nombre se moría por no poder cumplir un pacto con el diablo",
     "soñé con boy olmi",
     "soñé que alguien decía 'y si no somos inmortales porque no tomamos las decisiones correctas?'",
     "",
     "soñé que con @lumpenar comprábamos calabazas en Toledo e intentábamos cambiar las etiquetas del precio por otras más baratas",
     "las notificaciones de facebook están verdes o lo soñé?",
     "soñé que iba con la gata a una cervecería y teníamos toda una conversación",
     "soñé que hablaba con las pussy riot y que una ráfaga de viento me partía el cuerpo en dos",
     "soñé con un animal perfecto",
     "",
     "soñé con un asesino",
     "soñé toda la noche con una señora +60",
     "soñé con la casa X",
     "soñé con mi chakra raíz",
     "siempre soñé con trabajar en Emirates",
     "soñé que estaba toda golpeada",
     "soñé que mi padre me regalaba una bolsa de consorcio",
     "el otro día soñé que me leían los pies",
     "soñé que habían puesto transporte público en el mar, un tren que te llevaba de un lado a otro de la ciudad por el agua",
     "soñé que me encarcelaban por meter una moneda de otro país en una máquina de gaseosas",
     "soñé que me diagnosticaban fatiga crónica"

     
     
     
  ], 
   "      soñé": [
      "soñé que me apuntabas con un arma",
      "soñé que Marie Kondo se quedaba con toda mi ropa",
      "soñé que una serpiente nos atacaba",
      "soñé que alguien decía 'pero la muerte es agramatical'",
      "también soñé que vermelho era verde",
      "soñé que un patinador que siempre veo por la costa era una criatura no humana que había puesto la municipalidad para vigilar",
      "soñé con florencia y con el abogado",
      "soñé que caminaba de noche por una avenida que después se hacía ruta después se hacía puente y desembocaba en un barco. el barco me llevaba y yo pensaba 'uh pero si me lleva a otro país no tengo documento'. de repente aparecía la otra Fernanda Mugica y yo le robaba el documento",
      "soñé que me desvanecía pero en un teatro",
      "soñé que me encontraba a @conmigotampoco comprando en el Aragone",
      "dormí una siesta de cuatro horas y soñé que mi madre me contaba que había estado presa",
      "soñé que iba al cine, estaba de espaldas a la pantalla, veía al público reírse. cuando miraba la pantalla, veía que lo que se proyectaba era el público riéndose y comiendo pochoclo",
      "soñé que me decías que en lugar de apellido debería llevar un relincho",
      "",
      "soñé que iba al Anamora con Fabián Iriarte",
      "tb soñé que había una luciérnaga adentro de la casa",
      "soñé que comía arena y me preguntaba si me haría mal a los dientes",
      "soñé que Rocío me decía 'los gatos negros no perdonan' y Rocío soñó con un gato negro y ahora me manda foto de un gato negro",
      "soñé con un dinosaurio lila",
      "",
      "sueño recurrente en el que un tipo me tiene encerrada e intento escapar, pienso tengo las llaves, corro, cierro la puerta y lo encierro a él. despierto con el corazón a recontra mil",
      "soñé que le daba un abrazo a mi prima",
      "soñé que mi padre me pasaba por al lado como un refilón, una especie de meta-sueño",
      "soñé que iba a la peatonal sin barbijo y me daba cuenta y todo se ponía cámara lenta, había policías por todas partes",
      "soñé que pagaba con $5",
      "",
      "soñé que iba a Toledo y compraba yerba uruguaya para Diego y papel de fumar de los rugrats para Flavia",
      "soñé que alguien en videollamada buscaba sus anteojos y yo los encontraba en mi casa",
      "soñé que ponía unas fichas en el casino y salían unos pájaros que hacían una coreografía",
      "soñé que la gata jugaba en la ventana, a través del vidrio, con un gato igual a ella",
      "soñé que le pedía a mi ex analista que me recomendara un analista para ir de oyente",
      "soñé que descubría que siempre que aparecía una perra en literatura era la misma perra y decía 'guau, esta perra ya había aparecido en un cuento de Lugones y está acá, qué loco'",
      "soñé que tenía un motor en la mandíbula",
      "soñé con brea",
      "",
      "soñé que no me podían operar porque me olvidaba de hacer el ayuno, tenía que explicarle al médico y me decía 'ah un olvido freudiano'",
      "soñé que Alberto me convidaba cerveza en un tupper",
      "soñé que Néstor me estornudaba en la cara. Nestornudaba",
      "soñé que masticaba mis propios dientes",
      "soñé que le escribía un mensaje a alguien en la parte de atrás de una porción de pizza"


  ],
  "soñé      ": [
     
     "soñé que escribía un libro sobre la nieve",
     "",
     "soñé que ponía chubby checker para bailar",
    "alguien lo cambiaba y ponía una canción triste de calamaro y se reía de mí",
    "soñé que era el 2066 ",
    "caminaba sola en un supermercado toledo",
      "",
    "soñé que corría desquiciadamente",
    "para recuperar un paraguas blanco",
    "soñé que tomaba horas",
    "para trabajar en el baño de un boliche",
    "soñé con un lobo marino re lindo", 
     "",
     "soñé con sartre pero no puedo recordar qué",
     "soñé que mario ortiz me decía", 
     "el año que viene se van a usar los aparatos sin dientes",
     "",
     "soñé con betty draper",
     "soñé con telas y con roland barthes",
     "", 
     "soñé un pájaro azul", 
     "soñé que no existían las pocas personas que realmente quiero", 
     "soñé", 
     "que nos atacaban policías desde autos voladores", 
     "", 
     "soñé que godard había filmado una película en mar del plata en 1950", 
     "soñé que un perro me atacaba", 
     "soñé que iba a un cumpleaños y estaban todos en silencio", 
     "soñé que había una fiesta", 
     "en lo de mis vecinos jorge y laura", 
     "también soñé con pokèmon", 
     "", 
     "soñé q era el fin del mundo, había colectivos a los nuevos planetas, subía Néstor Kirchner y no tenía cargada la sube. nosotros le pagábamos el boleto",
     "ayer soñé que me sacaba un 2 (dos)",
     "soñé con La pérdida del reino de Bianco, sentía nostalgia de la época en que la leía",
     "soñé que le daba una bebé a los lobos", 
     "",
     "tengo lo que soñé en la punta de la lengua",
     ""

  ], 
  "soñé     ": [
     "soñé que elegía mal", 
     "soñé que vendían droga en El Cartucho Feliz",
     "soñé que abrazaba una nube en un edificio muy alto", 
     "no sé si soñé que me llegaba un mail o de verdad llegó", 
     "soñé que le decía a alguien suerte, éxitos, lo que haga falta", 
     "",
     "después soñé algo que me mató para siempre", 
     "", 
     "soñé que había una combinación de movimientos del cuerpo con la que te morías", 
     "soñé que un montón de zombies judíos venían a mar del plata", 
     "soñé que construíamos una casa en el mar, abajo del agua. echaba raíces y teníamos que declararla en afip", 
     "soñé con mi mamá y con otra persona llamada igual que ella", 
     "", 
     "soñé una temporada nueva y entera de Breaking Bad. Diego era walter white", 
     "soñé que buscaba en google y los resultados no eran personalizados. era muy ominoso", 
     "soñé que elegíamos lugares a donde ir en un mapa lleno de cadenas montañosas", 
     "soñé que un bebé me decía 'me quiero morir’", 
     "",
     "soñé con mi ex psicólogo", 
     "", 
     "soñé que no podía hablar y me sangraba mucho la nariz", 
     "soñé que me encontraba con mamá"
  
  ], 
  "soñé    ": [
     "9"
  ], 
  "soñé   ":[
     "10"
  ],
  "soñé  ":[
     "11"
  ],
  "soñé ":[
     "12"
  ]
    
   
   
   
 
};

